# Generated by Django 5.2.3 on 2025-06-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('date_upload', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
